# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.shop_unit_statistic_unit import ShopUnitStatisticUnit  # noqa: F401,E501
from swagger_server import util


class ShopUnitStatisticResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, items: List[ShopUnitStatisticUnit]=None):  # noqa: E501
        """ShopUnitStatisticResponse - a model defined in Swagger

        :param items: The items of this ShopUnitStatisticResponse.  # noqa: E501
        :type items: List[ShopUnitStatisticUnit]
        """
        self.swagger_types = {
            'items': List[ShopUnitStatisticUnit]
        }

        self.attribute_map = {
            'items': 'items'
        }
        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'ShopUnitStatisticResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ShopUnitStatisticResponse of this ShopUnitStatisticResponse.  # noqa: E501
        :rtype: ShopUnitStatisticResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[ShopUnitStatisticUnit]:
        """Gets the items of this ShopUnitStatisticResponse.

        История в произвольном порядке.  # noqa: E501

        :return: The items of this ShopUnitStatisticResponse.
        :rtype: List[ShopUnitStatisticUnit]
        """
        return self._items

    @items.setter
    def items(self, items: List[ShopUnitStatisticUnit]):
        """Sets the items of this ShopUnitStatisticResponse.

        История в произвольном порядке.  # noqa: E501

        :param items: The items of this ShopUnitStatisticResponse.
        :type items: List[ShopUnitStatisticUnit]
        """

        self._items = items
